import '@/assets/scss/globals.scss'
import Navigation from "@/global_components/Navigation"
import Footer from "@/global_components/Footer"
import AuthProvider from './context/AuthProvider'

import { Toaster } from 'sonner'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en" className='font-custom'>
            <body>
                <AuthProvider>
                    <Navigation />
                    {children}
                    <Footer />
                </AuthProvider>

                <Toaster richColors position="top-right" />
            </body>
        </html>
    )
}